SYMBOL = "ETH/USDT:USDT"  # Binance USDT 本位合约里的 ETH/USDT 交易对格式
TIMEFRAME = "1s"  # 使用 1 秒 K 线周期
FAST_EMA = 10  # 快线 EMA 周期，策略中的 10 EMA
SLOW_EMA = 30  # 慢线 EMA 周期，策略中的 30 EMA
STOP_LOSS_PCT = 0.10  # 止损比例，0.10 表示 10%
TAKE_PROFIT_PCT = 0.10  # 止盈比例，0.10 表示 10%
POSITION_FRACTION = 0.01  # 每次使用可用 USDT 的 1% 作为保证金
LEVERAGE = 100  # 实盘默认杠杆倍数，先用更稳妥的 100x
POLL_SECONDS = 1  # 每 1 秒检查一次行情和信号
PAPER_TRADING = False  # 模拟交易开关；改成 False 后会进入实盘分支
MARGIN_MODE = "ISOLATED"  # 合约保证金模式，默认使用逐仓
MAX_LIVE_LEVERAGE = 100  # 实盘默认允许的最大杠杆，和 Binance ETH 合约上限对齐
FUTURES_TAKER_FEE_PCT = 0.0005  # 市价单按 Binance USDT 本位合约 taker 手续费估算
LIVE_TRADING_ENV = "ENABLE_BINANCE_LIVE_TRADING"  # 允许真实下单的环境变量名
LIVE_TRADING_CONFIRM_VALUE = "I_UNDERSTAND_THIS_IS_REAL_MONEY"  # 允许真实下单时必须填写的确认值
ALLOW_HIGH_LEVERAGE_ENV = "ALLOW_HIGH_LEVERAGE"  # 允许高于 MAX_LIVE_LEVERAGE 的环境变量名
BINANCE_TESTNET_ENV = "BINANCE_TESTNET"  # 使用 Binance 测试网的环境变量名
FUTURES_WS_BASE_URL = "wss://fstream.binancefuture.com/ws"  # Binance USDT 合约 WebSocket 地址
FUTURES_TESTNET_WS_BASE_URL = "wss://stream.binancefuture.com/ws"  # Binance USDT 合约测试网 WebSocket 地址
REPORT_DIR = "reports"  # 交易记录和收益曲线保存目录
TRADE_HISTORY_CSV = "trades.csv"  # 每笔交易前后余额记录文件名
EQUITY_CURVE_PNG = "equity_curve.png"  # 账户余额曲线图片文件名
